version: '3'
services:
  web:
    image: springbootsample_web:1.0
    build: ./spring-boot-sample
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  data: