version: '3'
services:
  flask:
    image: springbootsample_flask:1.0
    build: ./python-flask-sample
    ports:
     - "5000:5000"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  web:
    image: springbootsample_web:1.0
    build: ./spring-boot-sample
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - shinkonetwork
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - shinkonetwork
networks:
  shinkonetwork:
